name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Assicurati che il branch principale sia "main" o personalizzalo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for Vite
        run: chmod +x ./node_modules/.bin/vite

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
